/**
 * Vehicle brands and models aligned with frontend.
 * Logo and model image URLs are resolved in the frontend by id.
 */

export const VEHICLE_BRANDS: { id: string; name: string; darkLogo?: boolean }[] = [
  { id: 'aito', name: 'Aito' },
  { id: 'audi', name: 'Audi', darkLogo: true },
  { id: 'bmw', name: 'BMW' },
  { id: 'byd', name: 'BYD' },
  { id: 'changan', name: 'Changan', darkLogo: true },
  { id: 'chevrolet', name: 'Chevrolet' },
  { id: 'citroen', name: 'Citroën' },
  { id: 'cupra', name: 'Cupra', darkLogo: true },
  { id: 'dongfeng', name: 'Dongfeng' },
  { id: 'fiat', name: 'Fiat' },
  { id: 'ford', name: 'Ford' },
  { id: 'gac-motor', name: 'GAC Motor', darkLogo: true },
  { id: 'geely', name: 'Geely' },
  { id: 'honda', name: 'Honda' },
  { id: 'hyundai', name: 'Hyundai' },
  { id: 'kia', name: 'Kia', darkLogo: true },
  { id: 'leapmotor', name: 'Leapmotor', darkLogo: true },
  { id: 'li-auto', name: 'Li Auto' },
  { id: 'lucid', name: 'Lucid' },
  { id: 'mercedes', name: 'Mercedes-Benz' },
  { id: 'nio', name: 'NIO', darkLogo: true },
  { id: 'nissan', name: 'Nissan' },
  { id: 'peugeot', name: 'Peugeot' },
  { id: 'polestar', name: 'Polestar' },
  { id: 'porsche', name: 'Porsche' },
  { id: 'renault', name: 'Renault' },
  { id: 'rivian', name: 'Rivian', darkLogo: true },
  { id: 'saic-motor', name: 'SAIC Motor' },
  { id: 'skoda', name: 'Škoda', darkLogo: true },
  { id: 'tesla', name: 'Tesla', darkLogo: true },
  { id: 'toyota', name: 'Toyota' },
  { id: 'vinfast', name: 'VinFast' },
  { id: 'volkswagen', name: 'Volkswagen' },
  { id: 'volvo', name: 'Volvo' },
  { id: 'xiaomi', name: 'Xiaomi' },
  { id: 'xpeng', name: 'XPeng' },
];

export const VEHICLE_MODELS: {
  id: string;
  brandId: string;
  name: string;
  powertrain: 'BEV' | 'PHEV' | 'EREV';
  connector: string[];
  imageUrl?: string;
}[] = [
  { id: 'model-s', brandId: 'tesla', name: 'Model S', powertrain: 'BEV', connector: ['NACS', 'CCS2'] },
  { id: 'model-x', brandId: 'tesla', name: 'Model X', powertrain: 'BEV', connector: ['NACS', 'CCS2'] },
  { id: 'model-3', brandId: 'tesla', name: 'Model 3', powertrain: 'BEV', connector: ['NACS', 'CCS2'] },
  { id: 'model-y', brandId: 'tesla', name: 'Model Y', powertrain: 'BEV', connector: ['NACS', 'CCS2'] },
  { id: 'cybertruck', brandId: 'tesla', name: 'Cybertruck', powertrain: 'BEV', connector: ['NACS', 'CCS2'] },
  { id: 'air', brandId: 'lucid', name: 'Lucid Air', powertrain: 'BEV', connector: ['J1772', 'CCS1'] },
  { id: 'gravity', brandId: 'lucid', name: 'Lucid Gravity', powertrain: 'BEV', connector: ['NACS'] },
  { id: 'r1t', brandId: 'rivian', name: 'Rivian R1T', powertrain: 'BEV', connector: ['CCS1', 'NACS'] },
  { id: 'r1s', brandId: 'rivian', name: 'Rivian R1S', powertrain: 'BEV', connector: ['CCS1', 'NACS'] },
  { id: 'r2', brandId: 'rivian', name: 'Rivian R2', powertrain: 'BEV', connector: ['NACS'] },
  { id: 'r3', brandId: 'rivian', name: 'Rivian R3 / R3X', powertrain: 'BEV', connector: ['NACS'] },
  { id: 'atto-3', brandId: 'byd', name: 'Atto 3 (Yuan Plus)', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'dolphin', brandId: 'byd', name: 'Dolphin', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'seal', brandId: 'byd', name: 'Seal', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'sealion-7', brandId: 'byd', name: 'Sealion 7 / Tang L EV', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'han-ev', brandId: 'byd', name: 'Han EV', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'emax-7', brandId: 'byd', name: 'eMAX 7 / eMAX MPV', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'e7', brandId: 'byd', name: 'e7', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'seagull', brandId: 'byd', name: 'Seagull (Dolphin Mini)', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'seal-u-dmi', brandId: 'byd', name: 'Seal U DM-i', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'seal-6-dmi', brandId: 'byd', name: 'Seal 6 DM-i', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'atto-2-dmi', brandId: 'byd', name: 'Atto 2 DM-i', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'song-plus-dmi', brandId: 'byd', name: 'Song Plus DM-i', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'qin-plus-dmi', brandId: 'byd', name: 'Qin Plus DM-i', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'han-dmi', brandId: 'byd', name: 'Han DM-i / DM-p', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'tang-dmi', brandId: 'byd', name: 'Tang DM-i / DM-p', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'frigate-07-dmi', brandId: 'byd', name: 'Frigate 07 DM-i', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'm5-erev', brandId: 'aito', name: 'AITO M5 (EREV)', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'm5-bev', brandId: 'aito', name: 'AITO M5 (BEV)', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'm9-erev', brandId: 'aito', name: 'AITO M9 (EREV)', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'm9-bev', brandId: 'aito', name: 'AITO M9 (BEV)', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'm8-erev', brandId: 'aito', name: 'AITO M8 (EREV)', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'm8-bev', brandId: 'aito', name: 'AITO M8 (BEV)', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'm7-erev', brandId: 'aito', name: 'AITO M7 (EREV)', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'q4-etron', brandId: 'audi', name: 'Q4 e-tron', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'q4-sportback-etron', brandId: 'audi', name: 'Q4 Sportback e-tron', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'q6-etron', brandId: 'audi', name: 'Q6 e-tron', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'q6-sportback-etron', brandId: 'audi', name: 'Q6 Sportback e-tron', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'sq6-etron', brandId: 'audi', name: 'SQ6 e-tron / SQ6 Sportback e-tron', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'a6-sportback-etron', brandId: 'audi', name: 'A6 Sportback e-tron', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 's6-sportback-etron', brandId: 'audi', name: 'S6 Sportback e-tron', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'etron-gt', brandId: 'audi', name: 'e-tron GT / S e-tron GT / RS e-tron GT', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'q5-etron', brandId: 'audi', name: 'Q5 e-tron', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'q5-tfsi-e', brandId: 'audi', name: 'Q5 TFSI e / Q5 e-hybrid', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'a3-sportback-etron', brandId: 'audi', name: 'A3 Sportback e-tron', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'a6-tfsi-e', brandId: 'audi', name: 'A6 TFSI e', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'q3-tfsi-e', brandId: 'audi', name: 'Q3 TFSI e', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'i3', brandId: 'bmw', name: 'BMW i3', powertrain: 'BEV', connector: ['CCS1', 'CCS2'] },
  { id: 'i4', brandId: 'bmw', name: 'BMW i4', powertrain: 'BEV', connector: ['CCS1', 'CCS2'] },
  { id: 'ix', brandId: 'bmw', name: 'BMW iX', powertrain: 'BEV', connector: ['CCS1', 'CCS2'] },
  { id: 'i5', brandId: 'bmw', name: 'BMW i5', powertrain: 'BEV', connector: ['CCS1', 'CCS2'] },
  { id: 'i7', brandId: 'bmw', name: 'BMW i7', powertrain: 'BEV', connector: ['CCS1', 'CCS2'] },
  { id: 'ix3', brandId: 'bmw', name: 'BMW iX3 (Neue Klasse)', powertrain: 'BEV', connector: ['CCS2'] },
  { id: '3-series-phev', brandId: 'bmw', name: 'BMW 3 Series PHEV (330e)', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: '5-series-phev', brandId: 'bmw', name: 'BMW 5 Series PHEV (530e)', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: '7-series-phev', brandId: 'bmw', name: 'BMW 7 Series PHEV (745e)', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'x3-phev', brandId: 'bmw', name: 'BMW X3 PHEV', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'x5-phev', brandId: 'bmw', name: 'BMW X5 PHEV', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'xm-phev', brandId: 'bmw', name: 'BMW XM / M-series PHEV', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'deepal-sl03-bev', brandId: 'changan', name: 'Deepal SL03 (BEV)', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'deepal-s07-bev', brandId: 'changan', name: 'Deepal S07 (BEV)', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'deepal-s05', brandId: 'changan', name: 'Deepal S05', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'deepal-e07-bev', brandId: 'changan', name: 'Deepal E07 / Nevo E07 (BEV)', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'deepal-l06-bev', brandId: 'changan', name: 'Deepal L06 (BEV)', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'deepal-sl03-erev', brandId: 'changan', name: 'Deepal SL03 (EREV)', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'deepal-s07-erev', brandId: 'changan', name: 'Deepal S07 (EREV)', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'deepal-e07-erev', brandId: 'changan', name: 'Deepal E07 / Nevo E07 (EREV)', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'deepal-l06-erev', brandId: 'changan', name: 'Deepal L06 (EREV)', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'nevo-q07', brandId: 'changan', name: 'Changan Nevo Q07', powertrain: 'PHEV', connector: ['GB_T'] },
  { id: 'bolt-ev', brandId: 'chevrolet', name: 'Chevrolet Bolt EV', powertrain: 'BEV', connector: ['J1772', 'CCS1'] },
  { id: 'bolt-euv', brandId: 'chevrolet', name: 'Chevrolet Bolt EUV', powertrain: 'BEV', connector: ['J1772', 'CCS1'] },
  { id: 'blazer-ev', brandId: 'chevrolet', name: 'Chevrolet Blazer EV', powertrain: 'BEV', connector: ['J1772', 'CCS1'] },
  { id: 'equinox-ev', brandId: 'chevrolet', name: 'Chevrolet Equinox EV', powertrain: 'BEV', connector: ['J1772', 'CCS1'] },
  { id: 'silverado-ev', brandId: 'chevrolet', name: 'Chevrolet Silverado EV', powertrain: 'BEV', connector: ['J1772', 'CCS1'] },
  { id: 'e-c3', brandId: 'citroen', name: 'ë-C3 / e-C3', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'e-c4', brandId: 'citroen', name: 'ë-C4 / e-C4', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'e-c4-x', brandId: 'citroen', name: 'ë-C4 X', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'e-berlingo', brandId: 'citroen', name: 'ë-Berlingo', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'e-spacetourer', brandId: 'citroen', name: 'ë-SpaceTourer', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'c5-x-phev', brandId: 'citroen', name: 'C5 X Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'c5-aircross-phev', brandId: 'citroen', name: 'C5 Aircross Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'born', brandId: 'cupra', name: 'Cupra Born', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'tavascan', brandId: 'cupra', name: 'Cupra Tavascan', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'raval', brandId: 'cupra', name: 'Cupra Raval', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'formentor-ehybrid', brandId: 'cupra', name: 'Cupra Formentor e-Hybrid', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'leon-ehybrid', brandId: 'cupra', name: 'Cupra Leon e-Hybrid', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'leon-sportstourer-ehybrid', brandId: 'cupra', name: 'Cupra Leon Sportstourer e-Hybrid', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'terramar-ehybrid', brandId: 'cupra', name: 'Cupra Terramar e-Hybrid', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'box', brandId: 'dongfeng', name: 'Dongfeng Box', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'nammi-06', brandId: 'dongfeng', name: 'Dongfeng Nammi 06 (Vigo)', powertrain: 'BEV', connector: ['GB_T', 'CCS2'] },
  { id: 'epi-007-bev', brandId: 'dongfeng', name: 'Dongfeng eπ 007 (BEV)', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'epi-008-bev', brandId: 'dongfeng', name: 'Dongfeng eπ 008 (BEV)', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'xinghai-s7-bev', brandId: 'dongfeng', name: 'Forthing Xinghai S7 (BEV)', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'lingxi-l', brandId: 'dongfeng', name: 'Lingxi L (Dongfeng-Honda)', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'epi-007-erev', brandId: 'dongfeng', name: 'Dongfeng eπ 007 (EREV)', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'epi-008-erev', brandId: 'dongfeng', name: 'Dongfeng eπ 008 (EREV)', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'xinghai-s7-erev', brandId: 'dongfeng', name: 'Forthing Xinghai S7 (EREV)', powertrain: 'EREV', connector: ['GB_T'] },
  { id: '500e', brandId: 'fiat', name: 'Fiat 500e', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'grande-panda-ev', brandId: 'fiat', name: 'Fiat Grande Panda Electric', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'mustang-mach-e', brandId: 'ford', name: 'Ford Mustang Mach-E', powertrain: 'BEV', connector: ['J1772', 'CCS1'] },
  { id: 'e-transit', brandId: 'ford', name: 'Ford E-Transit', powertrain: 'BEV', connector: ['J1772', 'CCS1'] },
  { id: 'f150-lightning', brandId: 'ford', name: 'Ford F-150 Lightning', powertrain: 'BEV', connector: ['J1772', 'CCS1'] },
  { id: 'puma-gen-e', brandId: 'ford', name: 'Ford Puma Gen-E', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'escape-phev', brandId: 'ford', name: 'Ford Escape Plug-In Hybrid', powertrain: 'PHEV', connector: ['J1772', 'TYPE_2'] },
  { id: 'explorer-phev', brandId: 'ford', name: 'Ford Explorer Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'ranger-phev', brandId: 'ford', name: 'Ford Ranger Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'aion-v', brandId: 'gac-motor', name: 'Aion V', powertrain: 'BEV', connector: ['GB_T', 'CCS2'] },
  { id: 'aion-ut', brandId: 'gac-motor', name: 'Aion UT', powertrain: 'BEV', connector: ['GB_T', 'CCS2'] },
  { id: 'aion-y', brandId: 'gac-motor', name: 'Aion Y / Aion Y Plus', powertrain: 'BEV', connector: ['GB_T', 'CCS2'] },
  { id: 'aion-rt', brandId: 'gac-motor', name: 'Aion RT', powertrain: 'BEV', connector: ['GB_T', 'CCS2'] },
  { id: 'aion-s', brandId: 'gac-motor', name: 'Aion S', powertrain: 'BEV', connector: ['GB_T', 'CCS2'] },
  { id: 'prologue', brandId: 'honda', name: 'Honda Prologue', powertrain: 'BEV', connector: ['J1772', 'CCS1'] },
  { id: 'e-ny1', brandId: 'honda', name: 'Honda e:Ny1 / e:Ny2', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'honda-e', brandId: 'honda', name: 'Honda e', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'clarity-phev', brandId: 'honda', name: 'Honda Clarity Plug-In Hybrid', powertrain: 'PHEV', connector: ['J1772'] },
  { id: 'cr-v-phev', brandId: 'honda', name: 'Honda CR-V Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'ioniq-5', brandId: 'hyundai', name: 'Hyundai IONIQ 5', powertrain: 'BEV', connector: ['CCS1', 'CCS2', 'NACS'] },
  { id: 'ioniq-6', brandId: 'hyundai', name: 'Hyundai IONIQ 6', powertrain: 'BEV', connector: ['CCS1', 'CCS2', 'NACS'] },
  { id: 'ioniq-9', brandId: 'hyundai', name: 'Hyundai IONIQ 9', powertrain: 'BEV', connector: ['CCS1', 'CCS2', 'NACS'] },
  { id: 'kona-ev', brandId: 'hyundai', name: 'Hyundai Kona Electric', powertrain: 'BEV', connector: ['CCS1', 'CCS2'] },
  { id: 'st1', brandId: 'hyundai', name: 'Hyundai ST1', powertrain: 'BEV', connector: ['CCS2'] },
  { id: 'ev6', brandId: 'kia', name: 'Kia EV6', powertrain: 'BEV', connector: ['CCS1', 'CCS2', 'NACS'] },
  { id: 'ev9', brandId: 'kia', name: 'Kia EV9', powertrain: 'BEV', connector: ['CCS1', 'CCS2', 'NACS'] },
  { id: 'niro-ev', brandId: 'kia', name: 'Kia Niro EV (e-Niro)', powertrain: 'BEV', connector: ['CCS1', 'CCS2'] },
  { id: 'soul-ev', brandId: 'kia', name: 'Kia Soul EV', powertrain: 'BEV', connector: ['CCS1', 'CCS2'] },
  { id: 'ev4', brandId: 'kia', name: 'Kia EV4', powertrain: 'BEV', connector: ['CCS1', 'CCS2', 'NACS'] },
  { id: 'ev2', brandId: 'kia', name: 'Kia EV2', powertrain: 'BEV', connector: ['CCS1', 'CCS2', 'NACS'] },
  { id: 'niro-phev', brandId: 'kia', name: 'Kia Niro Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'sportage-phev', brandId: 'kia', name: 'Kia Sportage Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'sorento-phev', brandId: 'kia', name: 'Kia Sorento Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'xceed-phev', brandId: 'kia', name: 'Kia XCeed Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 't03', brandId: 'leapmotor', name: 'Leapmotor T03', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'c01-bev', brandId: 'leapmotor', name: 'Leapmotor C01 (BEV)', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'c10', brandId: 'leapmotor', name: 'Leapmotor C10', powertrain: 'BEV', connector: ['GB_T', 'CCS2'] },
  { id: 'c11', brandId: 'leapmotor', name: 'Leapmotor C11', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'b10', brandId: 'leapmotor', name: 'Leapmotor B10', powertrain: 'BEV', connector: ['GB_T', 'CCS2'] },
  { id: 'b05', brandId: 'leapmotor', name: 'Leapmotor B05', powertrain: 'BEV', connector: ['CCS2'] },
  { id: 'c01-erev', brandId: 'leapmotor', name: 'Leapmotor C01 (EREV)', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'mega', brandId: 'li-auto', name: 'Li Auto MEGA', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'i8', brandId: 'li-auto', name: 'Li i8', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'i6', brandId: 'li-auto', name: 'Li i6', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'l6', brandId: 'li-auto', name: 'Li L6', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'l7', brandId: 'li-auto', name: 'Li L7', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'l8', brandId: 'li-auto', name: 'Li L8', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'l9', brandId: 'li-auto', name: 'Li L9', powertrain: 'EREV', connector: ['GB_T'] },
  { id: 'eqa', brandId: 'mercedes', name: 'Mercedes EQA', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'eqb', brandId: 'mercedes', name: 'Mercedes EQB', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'eqe-sedan', brandId: 'mercedes', name: 'Mercedes EQE Sedan', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'eqe-suv', brandId: 'mercedes', name: 'Mercedes EQE SUV', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'eqs-sedan', brandId: 'mercedes', name: 'Mercedes EQS Sedan', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'eqs-suv', brandId: 'mercedes', name: 'Mercedes EQS SUV', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'gla-ev', brandId: 'mercedes', name: 'Mercedes GLA EV', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'glc-ev', brandId: 'mercedes', name: 'Mercedes GLC EV', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'cla-ev', brandId: 'mercedes', name: 'Mercedes CLA EV', powertrain: 'BEV', connector: ['CCS1', 'NACS'] },
  { id: 'g580-eq', brandId: 'mercedes', name: 'Mercedes G 580 with EQ Technology', powertrain: 'BEV', connector: ['CCS2', 'CCS1'] },
  { id: 'glc-350e', brandId: 'mercedes', name: 'Mercedes GLC 350e 4MATIC PHEV', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'gle-450e', brandId: 'mercedes', name: 'Mercedes GLE 450e 4MATIC PHEV', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 's580e', brandId: 'mercedes', name: 'Mercedes S 580e PHEV', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'c300e', brandId: 'mercedes', name: 'Mercedes C 300e PHEV', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'amg-e53-phev', brandId: 'mercedes', name: 'Mercedes-AMG E 53 / C 63 E PERFORMANCE', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'es8', brandId: 'nio', name: 'NIO ES8', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'es7', brandId: 'nio', name: 'NIO ES7 / EL7', powertrain: 'BEV', connector: ['GB_T', 'CCS2'] },
  { id: 'es6', brandId: 'nio', name: 'NIO ES6 / EL6', powertrain: 'BEV', connector: ['GB_T', 'CCS2'] },
  { id: 'ec7', brandId: 'nio', name: 'NIO EC7', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'ec6', brandId: 'nio', name: 'NIO EC6', powertrain: 'BEV', connector: ['GB_T', 'CCS2'] },
  { id: 'et7', brandId: 'nio', name: 'NIO ET7', powertrain: 'BEV', connector: ['GB_T', 'CCS2'] },
  { id: 'et5', brandId: 'nio', name: 'NIO ET5', powertrain: 'BEV', connector: ['GB_T', 'CCS2'] },
  { id: 'et5-touring', brandId: 'nio', name: 'NIO ET5 Touring', powertrain: 'BEV', connector: ['CCS2'] },
  { id: 'et9', brandId: 'nio', name: 'NIO ET9', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'onvo-l60', brandId: 'nio', name: 'ONVO L60', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'leaf', brandId: 'nissan', name: 'Nissan LEAF', powertrain: 'BEV', connector: ['CHADEMO', 'TYPE_2'] },
  { id: 'ariya', brandId: 'nissan', name: 'Nissan Ariya', powertrain: 'BEV', connector: ['CCS1', 'CCS2'] },
  { id: 'townstar-ev', brandId: 'nissan', name: 'Nissan Townstar EV', powertrain: 'BEV', connector: ['CCS2'] },
  { id: 'e-nv200', brandId: 'nissan', name: 'Nissan e-NV200', powertrain: 'BEV', connector: ['CHADEMO'] },
  { id: 'rogue-phev', brandId: 'nissan', name: 'Nissan Rogue PHEV', powertrain: 'PHEV', connector: ['J1772', 'TYPE_2'] },
  { id: 'e-208', brandId: 'peugeot', name: 'Peugeot e-208', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'e-2008', brandId: 'peugeot', name: 'Peugeot e-2008', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'e-308', brandId: 'peugeot', name: 'Peugeot e-308 / e-308 SW', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'e-3008', brandId: 'peugeot', name: 'Peugeot e-3008', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'e-5008', brandId: 'peugeot', name: 'Peugeot e-5008', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'e-408', brandId: 'peugeot', name: 'Peugeot e-408', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'e-rifter', brandId: 'peugeot', name: 'Peugeot e-Rifter', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'e-partner', brandId: 'peugeot', name: 'Peugeot e-Partner', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'e-expert', brandId: 'peugeot', name: 'Peugeot e-Expert', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'e-boxer', brandId: 'peugeot', name: 'Peugeot e-Boxer', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: '308-hybrid', brandId: 'peugeot', name: 'Peugeot 308 Hybrid', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: '408-hybrid', brandId: 'peugeot', name: 'Peugeot 408 Hybrid', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: '3008-hybrid', brandId: 'peugeot', name: 'Peugeot 3008 Hybrid', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: '5008-hybrid', brandId: 'peugeot', name: 'Peugeot 5008 Hybrid', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: '508-hybrid', brandId: 'peugeot', name: 'Peugeot 508 Hybrid / 508 PSE', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'polestar-2', brandId: 'polestar', name: 'Polestar 2', powertrain: 'BEV', connector: ['CCS2', 'CCS1'] },
  { id: 'polestar-3', brandId: 'polestar', name: 'Polestar 3', powertrain: 'BEV', connector: ['CCS2', 'CCS1'] },
  { id: 'polestar-4', brandId: 'polestar', name: 'Polestar 4', powertrain: 'BEV', connector: ['CCS2', 'CCS1'] },
  { id: 'polestar-5', brandId: 'polestar', name: 'Polestar 5', powertrain: 'BEV', connector: ['CCS2', 'CCS1'] },
  { id: 'taycan', brandId: 'porsche', name: 'Porsche Taycan', powertrain: 'BEV', connector: ['CCS2', 'CCS1'] },
  { id: 'taycan-cross-turismo', brandId: 'porsche', name: 'Porsche Taycan Cross Turismo', powertrain: 'BEV', connector: ['CCS2', 'CCS1'] },
  { id: 'taycan-sport-turismo', brandId: 'porsche', name: 'Porsche Taycan Sport Turismo', powertrain: 'BEV', connector: ['CCS2', 'CCS1'] },
  { id: 'macan-electric', brandId: 'porsche', name: 'Porsche Macan Electric', powertrain: 'BEV', connector: ['CCS2', 'CCS1'] },
  { id: 'panamera-e-hybrid', brandId: 'porsche', name: 'Porsche Panamera E-Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'cayenne-e-hybrid', brandId: 'porsche', name: 'Porsche Cayenne E-Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'panamera-turbo-s-e-hybrid', brandId: 'porsche', name: 'Porsche Panamera Turbo S E-Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'cayenne-turbo-e-hybrid', brandId: 'porsche', name: 'Porsche Cayenne Turbo E-Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'megane-e-tech', brandId: 'renault', name: 'Renault Megane E-Tech Electric', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'scenic-e-tech', brandId: 'renault', name: 'Renault Scenic E-Tech Electric', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'zoe', brandId: 'renault', name: 'Renault Zoe', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'twingo-electric', brandId: 'renault', name: 'Renault Twingo Electric', powertrain: 'BEV', connector: ['TYPE_2'] },
  { id: 'kangoo-e-tech', brandId: 'renault', name: 'Renault Kangoo E-Tech Electric', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'master-e-tech', brandId: 'renault', name: 'Renault Master E-Tech Electric', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'trafic-e-tech', brandId: 'renault', name: 'Renault Trafic E-Tech Electric', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'captur-e-tech-phev', brandId: 'renault', name: 'Renault Captur E-Tech Plug-in', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'megane-e-tech-phev', brandId: 'renault', name: 'Renault Megane E-Tech Plug-in', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'mg4-ev', brandId: 'saic-motor', name: 'MG4 EV', powertrain: 'BEV', connector: ['CCS2', 'GB_T'] },
  { id: 'mgs6-ev', brandId: 'saic-motor', name: 'MGS6 EV', powertrain: 'BEV', connector: ['CCS2', 'GB_T'] },
  { id: 'mg-zs-ev', brandId: 'saic-motor', name: 'MG ZS EV', powertrain: 'BEV', connector: ['CCS2', 'GB_T'] },
  { id: 'rising-f7', brandId: 'saic-motor', name: 'Rising Auto F7', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'roewe-imax8-ev', brandId: 'saic-motor', name: 'Roewe iMAX8 EV', powertrain: 'BEV', connector: ['GB_T'] },
  { id: 'maxus-euniq5', brandId: 'saic-motor', name: 'Maxus EUNIQ 5 / MIFA 9 / eDeliver', powertrain: 'BEV', connector: ['CCS2', 'GB_T'] },
  { id: 'roewe-d7-phev', brandId: 'saic-motor', name: 'Roewe D7 PHEV', powertrain: 'PHEV', connector: ['TYPE_2', 'GB_T'] },
  { id: 'roewe-m7-dmh', brandId: 'saic-motor', name: 'Roewe M7 DMH', powertrain: 'PHEV', connector: ['TYPE_2', 'GB_T'] },
  { id: 'mg-ehs-phev', brandId: 'saic-motor', name: 'MG EHS Plug-in Hybrid', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'enyaq-iv', brandId: 'skoda', name: 'Škoda Enyaq iV', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'enyaq-coupe-iv', brandId: 'skoda', name: 'Škoda Enyaq Coupé iV', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'elroq', brandId: 'skoda', name: 'Škoda Elroq', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'epiq', brandId: 'skoda', name: 'Škoda Epiq', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'octavia-iv-phev', brandId: 'skoda', name: 'Škoda Octavia iV PHEV', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'superb-iv-phev', brandId: 'skoda', name: 'Škoda Superb iV PHEV', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'kodiaq-iv-phev', brandId: 'skoda', name: 'Škoda Kodiaq iV PHEV', powertrain: 'PHEV', connector: ['TYPE_2'] },
  { id: 'bz4x', brandId: 'toyota', name: 'Toyota bZ4X', powertrain: 'BEV', connector: ['CCS2', 'CCS1', 'NACS'] },
  { id: 'c-hr-plus', brandId: 'toyota', name: 'Toyota C-HR+ Electric', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'prius-prime', brandId: 'toyota', name: 'Toyota Prius Plug-In Hybrid / Prime', powertrain: 'PHEV', connector: ['J1772', 'TYPE_2'] },
  { id: 'rav4-phev', brandId: 'toyota', name: 'Toyota RAV4 Plug-in Hybrid', powertrain: 'PHEV', connector: ['J1772', 'TYPE_2'] },
  { id: 'rav4-phev-2026', brandId: 'toyota', name: 'Toyota RAV4 Plug-in Hybrid (2026+)', powertrain: 'PHEV', connector: ['CCS1'] },
  { id: 'c-hr-phev', brandId: 'toyota', name: 'Toyota C-HR Plug-in Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'vf6', brandId: 'vinfast', name: 'VinFast VF 6', powertrain: 'BEV', connector: ['CCS2', 'CCS1'] },
  { id: 'vf7', brandId: 'vinfast', name: 'VinFast VF 7', powertrain: 'BEV', connector: ['CCS2', 'CCS1'] },
  { id: 'vf8', brandId: 'vinfast', name: 'VinFast VF 8', powertrain: 'BEV', connector: ['CCS2', 'CCS1'] },
  { id: 'vf9', brandId: 'vinfast', name: 'VinFast VF 9', powertrain: 'BEV', connector: ['CCS2', 'CCS1'] },
  { id: 'vf-e34', brandId: 'vinfast', name: 'VinFast VF e34', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'id3', brandId: 'volkswagen', name: 'Volkswagen ID.3', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'id4', brandId: 'volkswagen', name: 'Volkswagen ID.4', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'id5', brandId: 'volkswagen', name: 'Volkswagen ID.5', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'id7', brandId: 'volkswagen', name: 'Volkswagen ID.7', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'id-buzz', brandId: 'volkswagen', name: 'Volkswagen ID.Buzz', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'id-polo', brandId: 'volkswagen', name: 'Volkswagen ID. Polo / ID. Cross', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'golf-gte', brandId: 'volkswagen', name: 'Volkswagen Golf GTE', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'passat-gte', brandId: 'volkswagen', name: 'Volkswagen Passat GTE', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'tiguan-ehybrid', brandId: 'volkswagen', name: 'Volkswagen Tiguan eHybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'arteon-ehybrid', brandId: 'volkswagen', name: 'Volkswagen Arteon eHybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'xc40-recharge-ev', brandId: 'volvo', name: 'Volvo XC40 Recharge Pure Electric', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'c40-recharge', brandId: 'volvo', name: 'Volvo C40 Recharge', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'ex30', brandId: 'volvo', name: 'Volvo EX30', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'ex90', brandId: 'volvo', name: 'Volvo EX90', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
  { id: 'xc40-recharge-phev', brandId: 'volvo', name: 'Volvo XC40 Recharge Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'xc60-recharge-phev', brandId: 'volvo', name: 'Volvo XC60 Recharge Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'xc90-recharge-phev', brandId: 'volvo', name: 'Volvo XC90 Recharge Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 's90-recharge-phev', brandId: 'volvo', name: 'Volvo S90 Recharge Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'v60-recharge-phev', brandId: 'volvo', name: 'Volvo V60 Recharge Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'v90-recharge-phev', brandId: 'volvo', name: 'Volvo V90 Recharge Plug-In Hybrid', powertrain: 'PHEV', connector: ['TYPE_2', 'J1772'] },
  { id: 'su7', brandId: 'xiaomi', name: 'Xiaomi SU7 / SU7 Max / SU7 Pro', powertrain: 'BEV', connector: ['GB_T', 'CCS2', 'CCS1'] },
  { id: 'yu7', brandId: 'xiaomi', name: 'Xiaomi YU7 / YU7 Pro / YU7 Max', powertrain: 'BEV', connector: ['GB_T', 'CCS2'] },
  { id: 'p7', brandId: 'xpeng', name: 'XPENG P7', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'g6', brandId: 'xpeng', name: 'XPENG G6', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'g9', brandId: 'xpeng', name: 'XPENG G9', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'p5', brandId: 'xpeng', name: 'XPENG P5', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2'] },
  { id: 'g3', brandId: 'xpeng', name: 'XPENG G3 / G3i', powertrain: 'BEV', connector: ['TYPE_2', 'CCS2', 'CCS1'] },
];
